# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

stages:
- stage: install_rust
  displayName: install rust
  jobs:
  - job: install_rustup
    displayName: install rustup
    steps:
    - script: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
      displayName: install rustup
    - script: rustup default nightly
      displayName: set nightly as default toolchain
    - script: rustup toolchain list
      displayName: verify install

- stage: posts_gen_test
  displayName: blog test
  jobs:
  - job: test_post_gen
    displayName: test post gen
    steps:
    - script: cargo test -p posts_gen
      displayName: test post gen

- stage: blog_test
  displayName: blog test
  dependsOn: install_rust
  jobs:
  - job: blog_test
    displayName: blog test
    steps:
    - script: rustup target add wasm32-unknown-unknown
      displayName: wasm target install
    - script: cargo build --target wasm32-unknown-unknown
      displayName: try blog build
