# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

stages:
- stage: posts_gen_test
  displayName: blog test
  jobs:
  - job: test_post_gen
    displayName: test post gen
    steps:
    - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
      displayName: install rustup
    - script: rustup default nightly
      displayName: set nightly as default
    - script: rustup update
      displayName: update toolchain
    - script: cargo test -p posts_gen
      displayName: test post gen

- stage: blog_test
  displayName: blog test
  dependsOn: []
  jobs:
  - job: blog_test
    displayName: blog test
    steps:
    - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
      displayName: install rustup
    - script: rustup default nightly
      displayName: set nightly as default
    - script: rustup update
      displayName: update toolchain
    - script: cargo --version
      displayName: verify cargo version
    - script: rustup toolchain list
      displayName: verify toolchain install
    - script: rustup target add wasm32-unknown-unknown
      displayName: wasm target install
    - script: cargo build --target wasm32-unknown-unknown
      displayName: try blog build
