# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

stages:
- stage: install_rust
  displayName: install rust
  jobs:
  - job: install_rustup
    displayName: install rustup
    steps:
    - script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      displayName: install rust - nightly

    - script: rustup toolchain list
      displayName: verify install

- stage: posts_gen_test
  displayName: blog test
  jobs:
  - job: test_post_gen
    displayName: test post gen
    steps:
    - script: cargo test -p posts_gen
      displayName: test post gen

- stage: blog_test
  displayName: blog test
  dependsOn: install_rust
  jobs:
  - job: blog_test
    displayName: blog test
    steps:
    - script: cargo install cargo-web
      displayName: install cargo-web
    - script: cargo web build -p blog --release
      displayName: try blog build
