[env]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "blog"

[tasks.static_file_win]
workspace = false
script_runner = "powershell"
script_extension = "ps1"
script = [
'''
Copy-Item .\source\* -Destination .\dist -Recurse -Force
Copy-Item .\post -Destination .\dist\ -Recurse -Force
'''
]

[tasks.static_file_unix]
workspace = false
script = [
'''
cp ./source/* dist -r
cp ./post dist/post -r
'''
]

[tasks.static_file]
workspace = false
run_task = [
    { name = "static_file_win", condition = { platforms = ["windows"] } },
    { name = "static_file_unix", condition = { platforms = ["mac", "linux"] } },
]

[tasks.parcel_win]
workspace = false
command = "node_modules\\.bin\\parcel.cmd"
args = ["index.html"]

[tasks.parcel]
workspace = false
run_task = [
    { name = "parcel_win", condition = { platforms = ["windows"] } },
]
