[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["."]
# Paths to ignore.
ignore = ["public/atom.xml", "public/posts.yml"]

[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = ["run", "--bin", "index_gen", "--release", "--", "public/post", "public"]
