runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  secrue: always
  static_files: index.html
  upload: index.html

- url: /(.*\..+)
  secrue: always
  static_files: \1
  upload: (.*)

- url: /.*
  secrue: always
  static_files: index.html
  upload: index.html
