[package]
name = "fubuki"
version = "1.1.0"
authors = [ "Gyara <me@gyara.moe>" ]
edition = "2018"

[lib]
crate-type = [ "rlib", "cdylib" ]

[dependencies]
serde_derive = "1.0.120"
log = "0.4.13"
wasm-bindgen = "0.2.69"
web_logger = {git = "https://github.com/Gyara-studio/web_logger.git"}
wasm-bindgen-futures = "0.4.19"
serde_yaml = "0.8.15"
yew = "0.17.4"
fubuki_types = {path = "../fubuki_types"}

  [dependencies.web-sys]
  version = "0.3.46"
  features = [
  "Location",
  "Window",
  "History",
  "EventTarget",
  "PopStateEvent",
  "Document",
  "Storage",
  "Response",
  "RequestInit",
  "RequestMode",
  "RequestCache",
]

  [dependencies.serde]
  version = "1.0.120"
  features = [ "derive" ]

  [dependencies.pulldown-cmark]
  version = "0.8.0"
  default-features = false

  [dependencies.getrandom]
  version = "0.2.2"
  features = [ "js" ]

[dev-dependencies]
wasm-bindgen-test = "0.3.20"

