[package]
name = "fubuki"
version = "4.2.0"
authors = ["Gyara <me@gyara.moe>"]
edition = "2021"

[dependencies]
fubuki_types = { path = "../fubuki_types" }
git-version = "0.3.5"
log = "0.4.14"
serde_derive = "1.0.136"
serde_yaml = "0.8.23"
stylist = { version = "0.10.0", features = ["yew_integration"] }
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.29"
web_logger = { git = "https://github.com/Gyara-studio/web_logger.git" }
yew = "0.19.3"
yew-agent = "0.1.0"
yew-router = "0.16.0"

[dependencies.web-sys]
version = "0.3.56"
features = [
  "Location",
  "Window",
  "History",
  "EventTarget",
  "PopStateEvent",
  "Document",
  "Storage",
  "Response",
  "RequestInit",
  "RequestMode",
  "RequestCache",
]

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dependencies.pulldown-cmark]
version = "0.9.1"
default-features = false

[dependencies.getrandom]
version = "0.2.5"
features = ["js"]

[dev-dependencies]
wasm-bindgen-test = "0.3.29"
