[package]
name = "fubuki"
version = "1.0.1"
authors = [ "Gyara <me@gyara.moe>" ]
edition = "2018"

[lib]
crate-type = [ "rlib", "cdylib" ]

[dependencies]
serde_derive = "1.0.112"
log = "0.4.11"
wasm-bindgen = "0.2.65"
web_logger = {git = "https://github.com/Gyara-studio/web_logger.git"}
wasm-bindgen-futures = "0.4.15"
serde_yaml = "0.8.13"
yew = "0.17.2"
fubuki_types = {path = "../fubuki_types"}

  [dependencies.web-sys]
  version = "0.3.40"
  features = [
  "Location",
  "Window",
  "History",
  "EventTarget",
  "PopStateEvent",
  "Document",
  "Storage",
  "Response",
  "RequestInit",
  "RequestMode",
  "RequestCache",
]

  [dependencies.serde]
  version = "1.0.112"
  features = [ "derive" ]

  [dependencies.pulldown-cmark]
  version = "0.7.1"
  default-features = false

  [dependencies.getrandom]
  version = "0.1.14"
  features = [ "wasm-bindgen" ]

[dev-dependencies]
wasm-bindgen-test = "0.3.14"

