[package]
name = "fubuki"
version = "0.9.1"
authors = [ "Gyara <me@gyara.moe>" ]
edition = "2018"

[lib]
crate-type = [ "rlib", "cdylib" ]

[dependencies]
serde_derive = "1.0.106"
log = "0.4.8"
wasm-bindgen = "0.2.62"
web_logger = {git = "https://github.com/Gyara-studio/web_logger.git"}
wasm-bindgen-futures = "0.4.12"
semver = "0.9.0"
serde_yaml = "0.8.11"

[dependencies.yew]
version = "0.15.0"

  [dependencies.web-sys]
  version = "0.3.37"
  features = [
  "Location",
  "Window",
  "History",
  "EventTarget",
  "PopStateEvent",
  "Document",
  "Storage",
  "Response",
  "RequestInit",
  "RequestMode",
  "RequestCache",
]

  [dependencies.serde]
  version = "1.0.106"
  features = [ "derive" ]

  [dependencies.pulldown-cmark]
  version = "0.7.0"
  default-features = false

  [dependencies.getrandom]
  version = "0.1.14"
  features = [ "wasm-bindgen" ]

[dev-dependencies]
wasm-bindgen-test = "0.3.11"

