[package]
name = "fubuki"
version = "0.6.0"
authors = [ "Gyara <me@gyara.moe>" ]
edition = "2018"

[lib]
crate-type = [ "rlib", "cdylib" ]

[dependencies]
serde_derive = "1.0.104"
yew = "0.13.0"
serde_json = "1.0.48"
log = "0.4.8"
web_logger = "0.2.0"
wasm-bindgen = "0.2.58"
wasm-bindgen-futures = "0.4.8"
semver = "0.9.0"

  [dependencies.web-sys]
  version = "0.3.35"
  features = [
  "Location",
  "Window",
  "History",
  "EventTarget",
  "PopStateEvent",
  "Document",
  "Storage",
  "Response",
  "RequestInit",
  "RequestMode",
  "RequestCache",
]

  [dependencies.serde]
  version = "1.0.104"
  features = [ "derive" ]

  [dependencies.pulldown-cmark]
  version = "0.7.0"
  default-features = false

  [dependencies.getrandom]
  version = "0.1.14"
  features = [ "wasm-bindgen" ]
