[package]
name = "fubuki"
version = "4.1.0"
authors = ["Gyara <me@gyara.moe>"]
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
fubuki_types = { path = "../fubuki_types" }
git-version = "0.3.5"
log = "0.4.14"
serde_derive = "1.0.130"
serde_yaml = "0.8.21"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
web_logger = { git = "https://github.com/Gyara-studio/web_logger.git" }
yew = "0.18.0"

[dependencies.web-sys]
version = "0.3.55"
features = [
  "Location",
  "Window",
  "History",
  "EventTarget",
  "PopStateEvent",
  "Document",
  "Storage",
  "Response",
  "RequestInit",
  "RequestMode",
  "RequestCache",
]

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.pulldown-cmark]
version = "0.8.0"
default-features = false

[dependencies.getrandom]
version = "0.2.3"
features = ["js"]

[dev-dependencies]
wasm-bindgen-test = "0.3.28"
