[package]
name = "blog"
version = "0.2.0"
authors = ["Gyara <me@gyara.moe>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = "1.0.90"
serde_derive = "1.0.90"
stdweb = "0.4.16"
yew = "0.6.0"
pulldown-cmark = { version = "0.4.1", default-features = false }
serde_json = "1.0.39"
