[package]
name = "blog"
version = "0.1.0"
authors = ["Gyara <me@gyara.moe>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde = "1"
serde_derive = "1"
stdweb = "0.4"
yew = "0.6.0"
pulldown-cmark = "0.1.2"
