[package]
name = "blog"
version = "0.4.0"
authors = ["Gyara <me@gyara.moe>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = "1.0.99"
serde_derive = "1.0.99"
stdweb = "0.4.18"
yew = "0.8.0"
pulldown-cmark = { version = "0.6.0", default-features = false }
serde_json = "1.0.40"
