[package]
name = "index_gen"
version = "4.0.0"
authors = ["Gyara <me@gyara.moe>"]
edition = "2021"

[dependencies]
serde_derive = "1.0.130"
serde_yaml = "0.8.21"
atom_syndication = "0.10.0"
htmlescape = "0.3.1"
fubuki_types = {path = "../fubuki_types"}
blake2 = "0.9.2"
base64 = "0.13.0"
anyhow = "1.0.44"

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.pulldown-cmark]
version = "0.8.0"
default-features = false
features = ["simd"]
