[package]
name = "index_gen"
version = "0.3.3"
authors = ["Gyara <me@gyara.moe>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.104"
serde_json = "1.0.50"
serde_yaml = "0.8.11"
atom_syndication = "0.8.0"
htmlescape = "0.3.1"

[dependencies.serde]
version = "1.0.104"
features = ["derive"]

[dependencies.pulldown-cmark]
version = "0.7.0"
default-features = false
features = ["simd"]
