[package]
name = "index_gen"
version = "1.0.0"
authors = ["Gyara <me@gyara.moe>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.120"
serde_yaml = "0.8.17"
atom_syndication = "0.9.1"
htmlescape = "0.3.1"
fubuki_types = {path = "../fubuki_types"}
blake2 = "0.9.1"
base64 = "0.13.0"
anyhow = "1.0.38"

[dependencies.serde]
version = "1.0.120"
features = ["derive"]

[dependencies.pulldown-cmark]
version = "0.8.0"
default-features = false
features = ["simd"]
