[package]
name = "index_gen"
version = "0.3.3"
authors = ["Gyara <me@gyara.moe>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.110"
serde_yaml = "0.8.12"
atom_syndication = "0.8.0"
htmlescape = "0.3.1"

[dependencies.serde]
version = "1.0.110"
features = ["derive"]

[dependencies.pulldown-cmark]
version = "0.7.1"
default-features = false
features = ["simd"]
