[package]
name = "posts_gen"
version = "0.2.0"
authors = ["Gyara <me@gyara.moe>"]
edition = "2018"

[dependencies]
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
serde_yaml = "0.8.9"
pulldown-cmark = "0.5.0"
atom_syndication = "0.6.0"
htmlescape = "0.3.1"
