name: Build

on:
  push:
    branches:
      - "roze"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly
    - uses: actions/setup-node@v3
    - name: Install Wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - uses: pnpm/action-setup@v2.2.1
    - name: build script
      run: ./scripts/build.sh
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOE_WORLD }}"
        expires: 30d
        projectId: ${{ secrets.PROJECT_ID }}
        channelId: live
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
    - name: publish change
      run: ./scripts/publish.sh
