name: build
on:
  push:
    branches:
      - "dev"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly
    - uses: actions/setup-node@v1
    - name: Install Wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.8.0
    - name: build script
      run: ./scripts/build.sh
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        expires: 30d
        projectId: ${{ secrets.PROJECT_ID }}
