name: Preview

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly
        targets: wasm32-unknown-unknown
    - uses: jetli/trunk-action@v0.2.0
    - name: build script
      run: ./scripts/build.sh
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOE_WORLD }}"
        expires: 7d
        projectId: ${{ secrets.PROJECT_ID }}
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
